### ISSUE TITLE
z/OS: Build fails wtih Node 8 beta

### ISSUE THREAD

**Issue by matthewpwilson** [RuntimeTools/omr-agentcore#84]
Using Node 8.16.0 on z/OS, the node-gyp build fails like this:
```
CTION omr_agentcore_binding_gyp_agentcore_target_Set_core_reported_version_build_level Release/obj.target/agentcore/geni/monitoring/agent/Agent.cpp
infile: ./src/ibmras/monitoring/agent/Agent.cpp
outfile: /u/wilson/git/appmetrics/build/Release/obj.target/agentcore/geni/monitoring/agent/Agent.cpp
Replacing '"99\.99\.99\.29991231"' with '"3.2.9.201906051606"'
  CXX(target) Release/obj.target/agentcore/omr-agentcore/src/ibmras/common/Logger.o
error: CNJ5200 The option "noconvlit" is not supported.
1 error generated.
Error while processing ../omr-agentcore/src/ibmras/common/Logger.cpp.
CNJ0793(I) Compilation failed for file ../omr-agentcore/src/ibmras/common/Logger.cpp.  Object file not created.
omr-agentcore/agentcore.target.mk:146: recipe for target 'Release/obj.target/agentcore/omr-agentcore/src/ibmras/common/Logger.o' failed
make: *** [Release/obj.target/agentcore/omr-agentcore/src/ibmras/common/Logger.o] Error 12
make: Leaving directory '/u/wilson/git/appmetrics/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/u/wilson/node/node-v8.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System OS/390 25.00
gyp ERR! command "/u/wilson/node/node-v8.16.0-os390-s390x/bin/node" "/u/wilson/node/node-v8.16.0-os390-s390x/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /u/wilson/git/appmetrics
gyp ERR! node -v v8.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appmetrics@5.0.0 install: `node showBuildInfo.js && node-gyp rebuild`
npm ERR! Exit status 1
```
Removing the 'qnoconvlit' option from binding.gyp resolves the problem. I don't think it should be needed as the new compiler runs in ASCII mode by default.  However this would likely break Node 6 on z/OS...

**Comment by mattcolegate** [comment]
@matthewpwilson As of appmetrics 5.0.0 we've removed support for Node 6, so that shouldn't be a problem. Are you willing to submit a PR for this? If so, please read https://github.com/RuntimeTools/omr-agentcore/blob/master/CONTRIBUTING.md and add your details to the https://github.com/runtimetools/omr-agentcore/blob/master/AUTHORS.md so we can accept it.

**Comment by grahamrawson** [comment]
The fix needed to RuntimeTools/omr-agentcore/binding.gyp doesn't seem to have made it to the public build. What needs to be done to make that happen?

**Comment by mattcolegate** [comment]
@grahamrawson A PR needs to be raised against RuntimeTools/omr-agentcore, following the guidelines in my previous comment.

**Comment by matthewpwilson** [comment]
Perhaps @gabylb you could make PR as it looks you have a fix?

**Comment by gabylb** [comment]
Sorry for the delay, just got back from vacation.
New PR: https://github.com/RuntimeTools/omr-agentcore/pull/91
